/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Documents
         * @description List every corpus document, merging on-disk facts with ingestion status.
         */
        get: operations["list_documents_admin_documents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/documents/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Document
         * @description Accept a document, store it under ``docs/<department>/``, queue ingestion.
         */
        post: operations["upload_document_admin_documents_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Document
         * @description Remove a document: its vector chunks, the file on disk, and its status row.
         */
        delete: operations["delete_document_admin_documents__document_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/documents/{document_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Document Status
         * @description Return one document's ingestion status.
         */
        get: operations["document_status_admin_documents__document_id__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/reindex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reindex
         * @description Rebuild the index from the corpus (hash-skip aware; only changed files re-embed).
         */
        post: operations["reindex_admin_reindex_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Revoke the current refresh token and clear the cookie.
         */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh
         * @description Rotate: validate the refresh cookie, revoke its jti, issue a fresh pair.
         */
        post: operations["refresh_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat
         * @description Send a message and receive an AI response with RAG context.
         *
         *     The user's role gates which document tiers are retrievable (RBAC).
         */
        post: operations["chat_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/history/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get History
         * @description Retrieve conversation history for a session.
         */
        get: operations["get_history_chat_history__session_id__get"];
        put?: never;
        post?: never;
        /**
         * Clear History
         * @description Clear conversation history for a session.
         */
        delete: operations["clear_history_chat_history__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sessions
         * @description List the caller's own conversations, most recently active first.
         */
        get: operations["list_sessions_chat_sessions_get"];
        put?: never;
        /**
         * Create Session
         * @description Create a new empty conversation owned by the caller.
         */
        post: operations["create_session_chat_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Session
         * @description Delete one of the caller's conversations and its messages.
         */
        delete: operations["delete_session_chat_sessions__session_id__delete"];
        options?: never;
        head?: never;
        /**
         * Rename Session
         * @description Rename one of the caller's conversations.
         */
        patch: operations["rename_session_chat_sessions__session_id__patch"];
        trace?: never;
    };
    "/chat/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat Stream
         * @description Stream the answer token-by-token over SSE.
         *
         *     Same auth/RBAC as ``POST /chat``; the body is identical. Emits typed events
         *     (token/sources/done/error). The service yields event dicts with a structured
         *     ``data`` payload; here we JSON-encode that payload onto the SSE ``data`` field.
         */
        post: operations["chat_stream_chat_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Preferences
         * @description Return the caller's preferences (defaults applied when unset).
         */
        get: operations["read_preferences_me_preferences_get"];
        /**
         * Update Preferences
         * @description Upsert the caller's preferences and return the merged result.
         */
        put: operations["update_preferences_me_preferences_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_document_admin_documents_upload_post */
        Body_upload_document_admin_documents_upload_post: {
            /** Department */
            department: string;
            /** File */
            file: string;
        };
        /**
         * ChatRequest
         * @description Body for ``POST /chat``.
         */
        ChatRequest: {
            /**
             * Message
             * @description The user's question.
             */
            message: string;
            /**
             * Session Id
             * @description Conversation id; each session keeps its own history.
             * @default demo
             */
            session_id: string;
        };
        /**
         * ChatResponse
         * @description Standardized envelope for ``POST /chat``.
         *
         *     ``status`` lets the client distinguish a grounded answer from a graceful
         *     non-answer without string-matching the prose: ``ok`` (answered),
         *     ``no_results`` (nothing found), ``blocked`` (RBAC-restricted), ``refused``
         *     (out of scope).
         */
        ChatResponse: {
            /**
             * Answer
             * @description The assistant's answer text.
             */
            answer: string;
            /**
             * Latency Ms
             * @description Server-side time to produce the answer.
             */
            latency_ms: number;
            /**
             * Session Id
             * @description The conversation id this reply belongs to.
             */
            session_id: string;
            /**
             * Sources
             * @description Cited documents behind the answer (empty when not grounded).
             */
            sources?: components["schemas"]["Source"][];
            /**
             * Status
             * @description ok | no_results | blocked | refused.
             */
            status: string;
        };
        /**
         * CreateSessionResponse
         * @description Response for ``POST /chat/sessions``.
         */
        CreateSessionResponse: {
            /**
             * Session Id
             * @description The newly created conversation id.
             */
            session_id: string;
        };
        /**
         * DeleteResponse
         * @description Response for ``DELETE /admin/documents/{document_id}``.
         */
        DeleteResponse: {
            /**
             * Deleted Chunks
             * @description Number of vector chunks removed from the index.
             */
            deleted_chunks: number;
            /**
             * Document Id
             * @description The document that was removed.
             */
            document_id: string;
        };
        /**
         * DocumentInfo
         * @description One corpus document, merging on-disk facts with ingestion status.
         */
        DocumentInfo: {
            /**
             * Department
             * @description Top-level folder the document lives under.
             */
            department: string;
            /**
             * Document Id
             * @description Path relative to docs/ (stable id), e.g. hr/employment-basics.md.
             */
            document_id: string;
            /**
             * Error
             * @description Failure reason when status is failed.
             */
            error?: string | null;
            /**
             * Size Bytes
             * @description File size on disk.
             */
            size_bytes: number;
            /**
             * Status
             * @description queued | processing | indexed | failed | unknown.
             */
            status: string;
            /**
             * Type
             * @description File extension without the dot (md/pdf/csv/...).
             */
            type: string;
            /**
             * Updated At
             * @description When the status last changed (ISO 8601).
             */
            updated_at?: string | null;
        };
        /**
         * DocumentStatusResponse
         * @description Response for ``GET /admin/documents/{document_id}/status``.
         */
        DocumentStatusResponse: {
            /**
             * Document Id
             * @description Path relative to docs/.
             */
            document_id: string;
            /**
             * Error
             * @description Failure reason when status is failed.
             */
            error?: string | null;
            /**
             * Status
             * @description queued | processing | indexed | failed.
             */
            status: string;
            /**
             * Updated At
             * @description When the status last changed (ISO 8601).
             */
            updated_at?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HistoryResponse
         * @description Response for ``GET /chat/history/{session_id}``.
         */
        HistoryResponse: {
            /**
             * History
             * @description Ordered {role, content} messages.
             */
            history?: {
                [key: string]: unknown;
            }[];
            /**
             * Session Id
             * @description The session the history belongs to.
             */
            session_id: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * MeResponse
         * @description Response for ``GET /auth/me``.
         */
        MeResponse: {
            /**
             * Email
             * @description Caller's email, when present in the token.
             */
            email?: string | null;
            /**
             * Id
             * @description User id.
             */
            id: number;
            /**
             * Region
             * @description Caller's home region.
             */
            region: string;
            /**
             * Role
             * @description Caller's role.
             */
            role: string;
        };
        /**
         * MessageResponse
         * @description Generic ``{"message": ...}`` acknowledgement.
         */
        MessageResponse: {
            /**
             * Message
             * @description Human-readable result.
             */
            message: string;
        };
        /**
         * PreferencesResponse
         * @description Response for ``GET/PUT /me/preferences`` (always complete via defaults).
         */
        PreferencesResponse: {
            /**
             * Language
             * @description Preferred answer language.
             */
            language: string;
            /**
             * Response Length
             * @description Preferred answer length.
             */
            response_length: string;
            /**
             * Tone
             * @description Preferred tone.
             */
            tone: string;
        };
        /**
         * ReindexResponse
         * @description Response for ``POST /admin/reindex``.
         */
        ReindexResponse: {
            /**
             * Deleted
             * @description Stale chunks removed before re-adding.
             */
            deleted: number;
            /**
             * Indexed
             * @description Chunks added in this run.
             */
            indexed: number;
            /**
             * Skipped
             * @description Files unchanged and skipped.
             */
            skipped: number;
        };
        /**
         * RenameSessionRequest
         * @description Body for ``PATCH /chat/sessions/{session_id}``.
         */
        RenameSessionRequest: {
            /**
             * Title
             * @description New session title.
             */
            title: string;
        };
        /**
         * SessionInfo
         * @description One conversation owned by the caller (list item for the sidebar).
         */
        SessionInfo: {
            /**
             * Session Id
             * @description Conversation id.
             */
            session_id: string;
            /**
             * Title
             * @description User-set title, if any.
             */
            title?: string | null;
            /**
             * Updated At
             * @description Last activity (ISO 8601).
             */
            updated_at?: string | null;
        };
        /**
         * Source
         * @description One cited chunk, in the frozen shape the React client binds to.
         */
        Source: {
            /**
             * Document Id
             * @description Stable doc id = path relative to docs/ (e.g. hr/x.md).
             */
            document_id: string;
            /**
             * File
             * @description Human-facing filename (basename of document_id).
             */
            file: string;
            /**
             * Section
             * @description Parent section heading, when known.
             */
            section?: string | null;
            /**
             * Source Type
             * @description Access tier the chunk came from (all/manager/hr_only).
             */
            source_type?: string | null;
        };
        /**
         * TokenResponse
         * @description Response for ``POST /auth/login`` and ``POST /auth/refresh``.
         */
        TokenResponse: {
            /**
             * Access Token
             * @description Short-lived bearer access token.
             */
            access_token: string;
            /**
             * Region
             * @description Caller's home region (us/india).
             */
            region: string;
            /**
             * Role
             * @description Caller's role (employee/manager/hr).
             */
            role: string;
            /**
             * Token Type
             * @description Always 'bearer'.
             * @default bearer
             */
            token_type: string;
        };
        /**
         * UpdatePreferencesRequest
         * @description Body for ``PUT /me/preferences``. Any field may be omitted/null to clear it.
         */
        UpdatePreferencesRequest: {
            /**
             * Language
             * @description Preferred answer language.
             */
            language?: string | null;
            /**
             * Response Length
             * @description short | medium | long.
             */
            response_length?: string | null;
            /**
             * Tone
             * @description e.g. friendly, formal, concise.
             */
            tone?: string | null;
        };
        /**
         * UploadResponse
         * @description Response for ``POST /admin/documents/upload``.
         */
        UploadResponse: {
            /**
             * Document Id
             * @description Path relative to docs/ assigned to the upload.
             */
            document_id: string;
            /**
             * Status
             * @description Initial status — always 'queued'; indexing runs in the background.
             */
            status: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_documents_admin_documents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentInfo"][];
                };
            };
        };
    };
    upload_document_admin_documents_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_admin_documents_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_document_admin_documents__document_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    document_status_admin_documents__document_id__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reindex_admin_reindex_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReindexResponse"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    refresh_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
        };
    };
    chat_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_history_chat_history__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_history_chat_history__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_chat_sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionInfo"][];
                };
            };
        };
    };
    create_session_chat_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateSessionResponse"];
                };
            };
        };
    };
    delete_session_chat_sessions__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_session_chat_sessions__session_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_stream_chat_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    read_preferences_me_preferences_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreferencesResponse"];
                };
            };
        };
    };
    update_preferences_me_preferences_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePreferencesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreferencesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
